services:
  marketplace-app:
    build:
      context: ./app
    depends_on:
      - marketplace-mongodb
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      - 35729:35729
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./app
          target: /usr/src/app
          action: sync

  marketplace-mongodb:
    image: mongo:6
    # comment out for no persist
    volumes:
      - database:/data/db
    ports:
      - 27017:27017

# comment out for no persist
volumes:
  database: